spring.application.name=library-system
# Enable the H2 Console (Web interface at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection (In-Memory)
# 'mem:testdb' means the data stays in RAM
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# This allows the browser to show the H2 frames
server.servlet.context-path=
spring.h2.console.settings.web-allow-others=true

# JPA Settings
# 'create-drop' ensures a clean slate every time you restart
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# 2. Tell Spring to run data.sql only AFTER the tables are created
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

# 3. Always run the script on startup (useful for H2)
spring.sql.init.mode=always